### PR TITLE
Allow running on Python 2 and Python 3

### PR DESCRIPTION
**Pull request by TayHobbs**
With the changes to the hashing algorithm in Python 3 the way that `_encode_payload` was sorting the payload would no longer consistently work. The solution found was to use the json.dumps sort_keys argument. This works consistently with Py2 and Py3, so that the signature created is the same between both.

### CODE REVIEW

**Comment by madisona** [comment]
@mattjmorrison, @TayHobbs @imtapps Is this safe? couldn't the order of items in json.dumps be very different, especially across python 2 and 3?  It is very little effort to get all the tests to pass (unchanged) except for the "test_get_signature_with_complex_non_unicode_payload" test.   This one fails on python 3 because a list of dictionaries can't be sorted rationally as the sort_vals method attempts. Apparently python 2 used to try to sort it anyways, but python3 blows up and says you can't 
compare two dictionaries

    File "/Users/amadison/projects/imtapps/apysigner/apysigner.py", line 29, in sort_vals
        return sorted(vals) if is_list(vals) else vals
    TypeError: unorderable types: dict() < dict()

Is that scenario we are providing legit? Or when we do have a complex data structure like that is it more appropriate to sign it using the json string and compare the signature against the json string before trying to turn it back into a python object?

**Comment by mattjmorrison** [comment]
This is safe and I believe highly preferable to the original implementation. `json.dumps` will retain a consistent order with the `sort_keys` option. This is probably the way that we should have done this from the start rather than trying to mess with creating a consistently ordered python dictionary.

**Comment by madisona** [comment]
@mattjmorrison @imtapps  Thanks for the review Matt. if that is the case, why don't we get rid of ALL our attempts to sort the payload. Check this out and see what you think:  https://github.com/madisona/apysigner/commit/db3e01c9e88775394e313c9febdc8689261d881a

The big thing we'll still need to be cognizant of is this fundamentally changes the signature for everything that wasn't already simply a string. In our own usage we'll need to ensure the projects using perl & c# are only trying to send & sign strings.

**Comment by stclair** [comment]
I can confirm that C# and Perl are only posting JSON strings.

**Comment by mattjmorrison** [comment]
@stclair @madisona if it is not strings on the perl / c# ends it wouldn't matter anyway because those languages wouldn't sort their data structures the same way anyway, so that wouldn't work to begin with. 

@madisona I think your changes look good except for this: https://github.com/madisona/apysigner/commit/db3e01c9e88775394e313c9febdc8689261d881a#diff-a1e5a6a906ff4f003499bdf030c5d0f0R41

I don't like seeing large blocks of copied & pasted code without any test cases. Just by looking at that code, is there a reason that calling `isoformat` for date/time objects is not adequate for nearly every scenario?

**Comment by madisona** [comment]
@mattjmorrison how about this.. I added tests.

The real argument is just that it appears to be a standard to show dates this way: See the reference to the ECMA-262 spec: http://ecma-international.org/ecma-262/5.1/#sec-15.9.1.15, and this stackoverflow post: http://stackoverflow.com/questions/10286204/the-right-json-date-format

The only differences really are that apparently ECMA only goes 3 places for microseconds and python goes 6 it appears. Also, with a UTC date instead of showing the offset as '+00:00' it is just a 'Z'

For our purposes here at work it probably isn't ever going to affect us in practice, but it seems like the right thing to do...  Looks like DRF is even more elaborate with the types of objects they try to handle properly.

**Comment by madisona** [comment]
@mattjmorrison You know, the more I think about it the more I agree that `isoformat` should be enough every time with dates & times. We're not dumping the json to be able to share it with anyone, we're just turning it into a string to create a reliable signature, nothing more.

**Comment by madisona** [comment]
@mattjmorrison How is this for a simplified go-forward version:  https://github.com/madisona/apysigner/blob/python3/apysigner.py

**Comment by mattjmorrison** [comment]
Looks good to me!

**Comment by madisona** [comment]
Thanks @TayHobbs for doing all the heavy lifting, and thanks @mattjmorrison for the reviews.  The new version is merged and up on pypi.

**Pull request closed without merging**
